---
title: "Example slide 25"
author: "Shane, Lizzie, Kesicia"
date: "February 14, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r set data}
library(MASS)
set.seed(6886)
data =mvrnorm(n=100, 
              mu=c(-2, 3),
              Sigma=matrix(c(8,3,3,2),
                           nrow=2,ncol=2))
                           colnames(data) =c('y','x')


#Separate the data into sections, Add a 1 to the x matrix because it's in the slide.
y <- data[,'y']
x <- data[,'x']
X <- cbind('a'=1,x)
```


```{r solve for beta}
#solve for slope and intercept that minimizes residuals

solve(t(X) %*%X)%*% t(X)%*% y

#returns an intercept of -6.4 and a beta value of 1.5
beta <- 1.5

```

```{r function}
e.e <- y-x*beta
sum.squared.residuals <- t(e.e)%*%(e.e)

cov.b <- function (k,l,m,n){         
  c = (l/(n-k)) * solve(t(m) %*% m)
   return(c)
}

#where k is the number of variables, l is the sum of squared residuals, m is the matrix of variables, and n is the number of observations.

cov.matrix <- as.matrix(cov.b(1, e.e, x, 100))

diag(cov.matrix)
#returns -.000042

```