---
title: "Untitled"
author: "Shane, Lizzie, Kesicia"
date: "February 14, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r create rows}
#set digits *does not give expected result, why?*

options(digits = 2)

#create rows
n.row <- c(length(polity$democ[!is.na(polity$democ)]),
           length(polity$autoc[!is.na(polity$autoc)]),
           length(polity$polity2[!is.na(polity$polity2)]),
           length(polity$xconst[!is.na(polity$xconst)])
)

na.row <- c(length(polity$democ[is.na(polity$democ)]),
           length(polity$autoc[is.na(polity$autoc)]),
           length(polity$polity2[is.na(polity$polity2)]),
           length(polity$xconst[is.na(polity$xconst)])
          )

mean.row <- c(mean(na.omit(polity$democ)), 
              mean(na.omit(polity$autoc)),
              mean(na.omit(polity$polity2)),
              mean(na.omit(polity$xconst))
)

median.row <- c(median(na.omit(polity$democ)), 
              median(na.omit(polity$autoc)),
              median(na.omit(polity$polity2)),
              median(na.omit(polity$xconst))
)
max.row <- c(max(na.omit(polity$democ)), 
               max(na.omit(polity$autoc)),
               max(na.omit(polity$polity2)),
               max(na.omit(polity$xconst))
)

min.row <- c(min(na.omit(polity$democ)), 
             min(na.omit(polity$autoc)),
             min(na.omit(polity$polity2)),
             min(na.omit(polity$xconst))
)

sd.row <- c(sd(na.omit(polity$democ)), 
            sd(na.omit(polity$autoc)),
            sd(na.omit(polity$polity2)),
            sd(na.omit(polity$xconst))
)

#combine rows into a matrix

summary.matrix <- matrix(c(n.row, 
                           na.row, 
                           mean.row, 
                           median.row, 
                           max.row, 
                           min.row, 
                           sd.row),
                         nrow=7, 
                         ncol=4,
                         byrow=TRUE
)

#Name the rows

row.names(summary.matrix) <- c("N", 
                               "NA", 
                               "Mean", 
                               "Median", 
                               "Max", 
                               "Min", 
                               "SD"
                               )
colnames(summary.matrix) <- c("democ", 
                              "autoc", 
                              "polity2", 
                              "xconst"
                              )

summary.matrix

```
